permalink: /:year/:month/:day/:title.html
#显示最新的10篇文章
paginate: 10
markdown: kramdown
#markdown: redcarpet

# 作者信息
author:
  name: whaozl
  email: whaozl@163.com
  link: http://whaozl.github.io
  weibo: http://weibo.com/zhulinniao
  github: http://github.com/whaozl
  music: http://www.xiami.com/collect/122047358?spm=a1z40.7113346.0.0&go=table
  linkedin: http://www.linkedin.com/in/whaozl
  cnblog: http://www.cnblogs.com/whaozl
  sinablog: http://blog.sina.com.cn/whaozl

# 站点信息
title: 郝竹林和王晓的blog
description: haozl and wangx's blog
url: http://whaozl.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
#ga:
#  id: UA-54262064-1
#  url: whaozl.github.io

# disqus 设置
#disqus:
#  shortname: whaozl
comments :
  provider : duoshuo
  duoshuo :
    short_name : whaozl

# 主题设置，自动激活某个标签
active: book

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新
  archive: 归档
  friendslink: 友情链接
