permalink: /:year/:month/:day/:title.html
#显示最新的10篇文章
paginate: 10
markdown: kramdown
#markdown: redcarpet

# 作者信息
author:
  name: 巫章鹏
  email: wzhangpeng1989@163.com
  link: https://pizitai.github.io
  weibo: https://weibo.com/u/3174688043
  github: https://github.com/pizitai
  music: 
  linkedin: https://www.linkedin.com/in/%E7%AB%A0%E9%B9%8F-%E5%B7%AB-485614105/
  cnblog: https://www.cnblogs.com/pizitai/
  sinablog: https://weibo.com/u/3174688043

# 站点信息
title: 巫章鹏的blog
description: 巫章鹏的个人博客
url: https://pizitai.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/wzp.jpg
favicon: /public/img/favicon.ico

# google analytics 设置
#ga:
#  id: UA-54262064-1
#  url: whaozl.github.io

# disqus 设置
#disqus:
#  shortname: whaozl
comments :
  provider : duoshuo
  duoshuo :
    short_name : whaozl

# 主题设置，自动激活某个标签
active: book

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新
  archive: 归档
  friendslink: 友情链接
